<?php
/**
 * @file
 * Install, update and uninstall functions for the drop_enterprise install profile.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function drop_enterprise_install() {
  // Add text formats.

  !function_exists('spark_install') ? require_once('profiles/spark/spark.install') : FALSE;
  call_user_func('spark_install');


}
